general.import = ["ep4.toml"]

general.live_config_reload = true

[font]
size = 15.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
#On windows "Liberation Mono"
family = "LiberationMono"
style = "Regular"

# Decomment on windows.
#[terminal.shell]
#program = "C:\\Windows\\System32\\cmd.exe"

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
